apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: node-red-example-el
spec:
  podTemplate: {}
  serviceAccountName: pipeline
  triggers:
    - bindings:
        - kind: TriggerBinding
          ref: node-red-example-tb
      template:
        name: node-red-example-template
