apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
  - route.yaml
commonLabels:
  app: node-red-example
  app.kubernetes.io/instance: node-red-example-app-instance
  app.kubernetes.io/name: node-red-example